version: "3.8"
x-environment-defaults: &environment-defaults
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_PORT: 5432
  GEMINI_API_KEY: "${GEMINI_API_KEY}"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network
    ports:
      - "5432:5432"
    restart: on-failure:5

  app:
    build:
      context: ./app
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      <<: *environment-defaults
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - api-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - api-network
    restart: on-failure:5

  test:
    build:
      context: ./app
    container_name: fastapi_app_test
    depends_on:
      - db
    environment:
      <<: *environment-defaults
      DB_HOST: db
    volumes:
      - .:/app
    networks:
      - api-network
    entrypoint:
      [
        "pytest",
        "--maxfail=5",
        "--disable-warnings",
        "-q",
        "--cov=app",
        "--cov-report=term-missing",
      ]
    profiles:
      - test

networks:
  api-network:
    driver: bridge

volumes:
  postgres_data:
